version: '3.8'

services:
  image-sync:
    build: .
    # 如不愿意构建也可以直接使用我的镜像，把上面build注释，下面的image取消注释即可
    # image: registry.cn-hangzhou.aliyuncs.com/syncimage2aliyun/syncimage2aliyun:0.1
    container_name: image-sync-service
    ports:
      - "${PORT:-3000}:${PORT:-3000}"
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000/health', (r) => {process.exit(r.statusCode === 200 ? 0 : 1)})"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 5s

