name: Docker Image Sync

on:
  push:
    branches:
      - main
      - master
    paths:
      - 'images.txt'

jobs:
  sync-images:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Log in to target Docker registry
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin ${{ secrets.DOCKER_REGISTRY }}
      
      - name: Sync images
        id: sync
        run: |
          echo "正在读取 images.txt..."
          echo "文件内容："
          cat images.txt
          echo ""
          
          # 定义同步函数
          sync_image() {
            local line="$1"
            local job_num="$2"
            
            # 跳过空行和注释
            if [[ -z "$line" ]] || [[ "$line" =~ ^[[:space:]]*# ]]; then
              echo "任务 $job_num: 跳过空行或注释"
              return 0
            fi
            
            echo ""
            echo "========================================"
            echo "任务 $job_num: 开始处理"
            echo "原始行: $line"
            echo "========================================"
            
            # 提取 platform 参数
            platform=""
            if [[ "$line" =~ --platform=([^[:space:]]+) ]]; then
              platform="${BASH_REMATCH[1]}"
              line=$(echo "$line" | sed 's/--platform=[^[:space:]]*[[:space:]]*//' | sed 's/^[[:space:]]*//' | sed 's/[[:space:]]*$//')
              echo "检测到平台参数: $platform"
              echo "处理后的行: $line"
            fi
            
            # 解析格式: <源镜像> to <目标镜像>:<标签>
            if [[ "$line" =~ ^([^[:space:]]+)[[:space:]]+to[[:space:]]+([^[:space:]]+):([^[:space:]]+)$ ]]; then
              source="${BASH_REMATCH[1]}"
              target="${BASH_REMATCH[2]}"
              tag="${BASH_REMATCH[3]}"
              full_target="${target}:${tag}"
              
              echo "源镜像: $source"
              echo "目标镜像: $full_target"
              echo "平台: ${platform:-默认}"
              echo ""
              
              # 拉取镜像
              echo "任务 $job_num: 开始拉取镜像..."
              pull_success=0
              
              if [[ -n "$platform" ]]; then
                echo "执行: docker pull --platform=$platform $source"
                if docker pull --platform="$platform" "$source" 2>&1; then
                  pull_success=1
                  echo "✅ 任务 $job_num: 拉取成功"
                else
                  echo "❌ 任务 $job_num: 拉取失败"
                fi
              else
                echo "执行: docker pull $source"
                if docker pull "$source" 2>&1; then
                  pull_success=1
                  echo "✅ 任务 $job_num: 拉取成功"
                else
                  echo "❌ 任务 $job_num: 拉取失败"
                fi
              fi
              
              if [[ $pull_success -eq 1 ]]; then
                # 标记镜像
                echo "执行: docker tag $source $full_target"
                if docker tag "$source" "$full_target" 2>&1; then
                  echo "✅ 任务 $job_num: 标记成功"
                  
                  # 推送镜像
                  echo "执行: docker push $full_target"
                  if docker push "$full_target" 2>&1; then
                    echo "✅ 任务 $job_num: 推送成功"
                    echo "SUCCESS:$source -> $full_target" >> "$temp_results"
                  else
                    echo "❌ 任务 $job_num: 推送失败"
                    echo "FAILED:$source -> $full_target" >> "$temp_results"
                  fi
                else
                  echo "❌ 任务 $job_num: 标记失败"
                  echo "FAILED:$source -> $full_target" >> "$temp_results"
                fi
              else
                echo "❌ 任务 $job_num: 操作失败"
                echo "FAILED:$source -> $full_target" >> "$temp_results"
              fi
            else
              echo "⚠️  任务 $job_num: 无法解析此行，跳过"
            fi
          }
          
          # 导出函数
          export -f sync_image
          
          # 创建临时结果文件
          temp_results=$(mktemp)
          export temp_results
          
          # 收集所有任务
          job_num=0
          pids=()
          
          while IFS= read -r line; do
            ((job_num++))
            echo "启动后台任务 $job_num"
            sync_image "$line" "$job_num" &
            pids+=($!)
          done < images.txt
          
          echo ""
          echo "总共启动了 $job_num 个任务"
          echo "等待所有任务完成..."
          
          # 等待所有后台任务
          for pid in "${pids[@]}"; do
            wait "$pid"
          done
          
          echo ""
          echo "所有任务已完成"
          
          # 统计结果
          success_count=$(grep -c "^SUCCESS:" "$temp_results" 2>/dev/null || echo "0")
          failed_count=$(grep -c "^FAILED:" "$temp_results" 2>/dev/null || echo "0")
          
          echo ""
          echo "========================================"
          echo "镜像同步完成"
          echo "成功: $success_count"
          echo "失败: $failed_count"
          echo "========================================"
          
          # 显示失败的镜像
          if [[ $failed_count -gt 0 ]]; then
            echo ""
            echo "失败的镜像："
            grep "^FAILED:" "$temp_results" || true
          fi
          
          # 清理临时文件
          rm -f "$temp_results"
          
          if [ "$failed_count" -gt 0 ]; then
            echo "failed=true" >> $GITHUB_OUTPUT
            exit 1
          else
            echo "所有镜像同步成功！"
            echo "failed=false" >> $GITHUB_OUTPUT
          fi
      
      - name: Clean up
        if: always()
        run: |
          echo "清理本地镜像..."
          docker image prune -f
          docker system prune -f
      
      - name: Summary
        if: always()
        run: |
          if [ "${{ steps.sync.outputs.failed }}" = "true" ]; then
            echo "❌ 部分镜像同步失败"
            echo "${{ steps.sync.outputs.failed_list }}"
            exit 1
          else
            echo "✅ 所有镜像同步成功"
          fi

